import pandas as pd
import streamlit as st
import description # Description module

# Prompt to some description which sql code you would like to generate
def get_prompt():
    prompt = st.text_input("What would you like to know?", key="prompt")
    return prompt;

# Set up the title of Streamlit app
st.set_page_config(page_title="Data Analysis App", page_icon="📊", layout="wide")

# Set up the sidebar
st.sidebar.header("Navigation")

# Set up some layout for main page
st.title("Database Analysis Procedure")

st.markdown(
    body='''
        ## Purpose \n 
        1. Analyzing the database with Natural Language Programming (NLP) \n
        2. Recommend what kinds of analysis you can try from this app. \n
        3. Visualize what you would like to see. \n

'''
)

st.divider()
st.session_state.prompt_sentence = get_prompt()
    

# #Create a connection to the database
# sql = set_up_sql.DatabaseManager()
# sql.connect('sqlite:///cyber_security.db')
# sql.create_table(df)

# gemini = Gemini_API.geminiAPI(df.columns.tolist())  # Pass the column names to the geminiAPI instance
# gemini.configure()

# in_prompt = get_prompt()  # Get the prompt from streamlit input
# if in_prompt:
#     st.write("Prompt received:", in_prompt)  # Display the prompt in the Streamlit app
#     gemini.execute_prompt(in_prompt)  # Execute the prompt using the geminiAPI instance
#     st.write("SQL Query generated by the model:", extract_select_statements(''.join(gemini.buffer)))  # Display the SQL query generated by the model
#     sql.execute_query(''.join(gemini.buffer)[7:-3])  # Execute the SQL query using the DatabaseManager instance


#     # st.write("Table Format")c
#     # st.table(df_result)
#     #print(sql.response)  # Print the response from the geminiAPI instance

#     #print("SQL Query:", ''.join(gemini.buffer))  # Print the SQL query generated by the model


